// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PIM4_backend.Data;

#nullable disable

namespace PIM4_backend.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251019010136_NomeDaMigration")]
    partial class NomeDaMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Departamento", b =>
                {
                    b.Property<int>("IdDepartamento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdDepartamento"));

                    b.Property<string>("Descricao")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("IdDepartamento");

                    b.ToTable("Departamentos");
                });

            modelBuilder.Entity("PIM4_backend.Models.Categoria", b =>
                {
                    b.Property<int>("IdCategoria")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCategoria"));

                    b.Property<string>("Descricao")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("IdCategoria");

                    b.ToTable("Categorias");
                });

            modelBuilder.Entity("PIM4_backend.Models.Chamado", b =>
                {
                    b.Property<int>("IdChamado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdChamado"));

                    b.Property<DateTime>("DataAbertura")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataFechamento")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descricao")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("IdCategoria")
                        .HasColumnType("int");

                    b.Property<int>("IdStatus")
                        .HasColumnType("int");

                    b.Property<int?>("IdTecnicoResponsavel")
                        .HasColumnType("int");

                    b.Property<int>("IdUsuarioSolicitante")
                        .HasColumnType("int");

                    b.Property<string>("Prioridade")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("IdChamado");

                    b.HasIndex("IdCategoria");

                    b.HasIndex("IdStatus");

                    b.HasIndex("IdTecnicoResponsavel");

                    b.HasIndex("IdUsuarioSolicitante");

                    b.ToTable("Chamados");
                });

            modelBuilder.Entity("PIM4_backend.Models.Interacao", b =>
                {
                    b.Property<int>("IdInteracao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdInteracao"));

                    b.Property<DateTime>("DataInteracao")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdAutor")
                        .HasColumnType("int");

                    b.Property<int>("IdChamado")
                        .HasColumnType("int");

                    b.Property<string>("Mensagem")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.HasKey("IdInteracao");

                    b.HasIndex("IdAutor");

                    b.HasIndex("IdChamado");

                    b.ToTable("Interacoes");
                });

            modelBuilder.Entity("PIM4_backend.Models.LogAtividade", b =>
                {
                    b.Property<int>("IdLog")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdLog"));

                    b.Property<string>("Acao")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("DataAcao")
                        .HasColumnType("datetime2");

                    b.Property<string>("EnderecoIP")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("int");

                    b.HasKey("IdLog");

                    b.HasIndex("IdUsuario");

                    b.ToTable("LogsAtividades");
                });

            modelBuilder.Entity("PIM4_backend.Models.RespostaIA", b =>
                {
                    b.Property<int>("IdRespostaIA")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdRespostaIA"));

                    b.Property<DateTime>("DataGeracao")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdChamado")
                        .HasColumnType("int");

                    b.Property<string>("IdExecucaoN8N")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Mensagem")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Modelo")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("IdRespostaIA");

                    b.HasIndex("IdChamado");

                    b.ToTable("RespostasIA");
                });

            modelBuilder.Entity("PIM4_backend.Models.StatusChamado", b =>
                {
                    b.Property<int>("IdStatus")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdStatus"));

                    b.Property<string>("Descricao")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("IdStatus");

                    b.ToTable("StatusChamados");
                });

            modelBuilder.Entity("PIM4_backend.Models.Usuario", b =>
                {
                    b.Property<int>("IdUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdUsuario"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("IdDepartamento")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Perfil")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("SenhaHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdUsuario");

                    b.HasIndex("IdDepartamento");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("PIM4_backend.Models.Chamado", b =>
                {
                    b.HasOne("PIM4_backend.Models.Categoria", "Categoria")
                        .WithMany("Chamados")
                        .HasForeignKey("IdCategoria")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PIM4_backend.Models.StatusChamado", "StatusChamado")
                        .WithMany("Chamados")
                        .HasForeignKey("IdStatus")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PIM4_backend.Models.Usuario", "TecnicoResponsavel")
                        .WithMany("ChamadosAtribuidos")
                        .HasForeignKey("IdTecnicoResponsavel")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("PIM4_backend.Models.Usuario", "UsuarioSolicitante")
                        .WithMany("ChamadosAbertos")
                        .HasForeignKey("IdUsuarioSolicitante")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Categoria");

                    b.Navigation("StatusChamado");

                    b.Navigation("TecnicoResponsavel");

                    b.Navigation("UsuarioSolicitante");
                });

            modelBuilder.Entity("PIM4_backend.Models.Interacao", b =>
                {
                    b.HasOne("PIM4_backend.Models.Usuario", "Autor")
                        .WithMany("Interacoes")
                        .HasForeignKey("IdAutor")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PIM4_backend.Models.Chamado", "Chamado")
                        .WithMany("Interacoes")
                        .HasForeignKey("IdChamado")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Autor");

                    b.Navigation("Chamado");
                });

            modelBuilder.Entity("PIM4_backend.Models.LogAtividade", b =>
                {
                    b.HasOne("PIM4_backend.Models.Usuario", "Usuario")
                        .WithMany("LogsAtividades")
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("PIM4_backend.Models.RespostaIA", b =>
                {
                    b.HasOne("PIM4_backend.Models.Chamado", "Chamado")
                        .WithMany("RespostasIA")
                        .HasForeignKey("IdChamado")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Chamado");
                });

            modelBuilder.Entity("PIM4_backend.Models.Usuario", b =>
                {
                    b.HasOne("Departamento", "Departamento")
                        .WithMany("Usuarios")
                        .HasForeignKey("IdDepartamento");

                    b.Navigation("Departamento");
                });

            modelBuilder.Entity("Departamento", b =>
                {
                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("PIM4_backend.Models.Categoria", b =>
                {
                    b.Navigation("Chamados");
                });

            modelBuilder.Entity("PIM4_backend.Models.Chamado", b =>
                {
                    b.Navigation("Interacoes");

                    b.Navigation("RespostasIA");
                });

            modelBuilder.Entity("PIM4_backend.Models.StatusChamado", b =>
                {
                    b.Navigation("Chamados");
                });

            modelBuilder.Entity("PIM4_backend.Models.Usuario", b =>
                {
                    b.Navigation("ChamadosAbertos");

                    b.Navigation("ChamadosAtribuidos");

                    b.Navigation("Interacoes");

                    b.Navigation("LogsAtividades");
                });
#pragma warning restore 612, 618
        }
    }
}
